### ISSUE TITLE
Unable to initialize modular input "azure_diagnostic_logs" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_diagnostic_logs: script running failed (exited with code 1).

### ISSUE THREAD

**Issue by mlinstrom1** [microsoft/AzureMonitorAddonForSplunk#109]
node -v v6.14.3
Azure Monitor add-on version 1.3.1
Python 2.7.5
centos-release-7-5.1804.4.el7.centos.x86_64
SPLUNK enterprise version 6.5.2

I am at a loss as I still am getting the error "Unable to initialize modular input "azure_diagnostic_logs" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_diagnostic_logs: script running failed (exited with code 1)."

The app is installed on one of my search heads. I have a separate indexer, deployment server, and Enterprise Security Search Head.  I have no input options for the app via the GUI.

Any help would be greatly appreciated.

**Comment by sebastus** [comment]
Are any of the data inputs working?

**Comment by sebastus** [comment]
Did you install the python and node.js dependencies?

**Comment by mlinstrom1** [comment]
Yes. node -v v6.14.3, I manually ran am_depends_rhel.sh. The only issue I get from that is a few "Target directory /etc/apps/TA-Azure_Monitor/bin/certifi already exists. Specify --upgrade to force replacement".

**Comment by sebastus** [comment]
I don't recognize the certifi  folder - what is it?

Did you do "npm install" from within the bin/app folder?

**Comment by mlinstrom1** [comment]
I ran this as root " npm install" 
and received "command not found"
I thought I ran a command yesterday to see if it was already installed but suspect I did not.

**Comment by sebastus** [comment]
npm is the node.js package manager. Your computer may already have node.js
installed, but npm may not be. bottom line, the node packages must be
installed and npm is how I do it. when node is installed on one of my
computers and npm is not, I simply install node again from nodejs.org and
it includes npm.

**Comment by mlinstrom1** [comment]
This is what I get after install node and running npm install:
Installed:
  nodejs.x86_64 2:6.15.1-1nodesource

Complete!
[root@asrsh01 app]# npm install
npm WARN enoent ENOENT: no such file or directory, open '/etc/apps/TA-Azure_Monitor/bin/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
[root@asrsh01 app]# ^C
[root@asrsh01 app]#

**Comment by sebastus** [comment]
great! restart TA - see data inputs?

**Comment by mlinstrom1** [comment]
Thank you for your help sebastus !

**Comment by yorokobi** [comment]
I'm running into the exact same issue.

Enterprise Splunk 6.5.6
RHEL 7.4
node 6.14.3

Here's what I've tried

- Cloned the repo
- Untarred the package (1.3.1) to `$SPLUNK_HOME/etc/apps/`
- Stopped Splunk
- Ensured all Splunk-related processes were not present in `ps -ef`
- Started Splunk
- Disabled the app
- As the `root` user, manually installed the PIP modules to `$SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin` and `$SPLUNK_HOME/etc/apps/TA-Azure_Monitor/app/bin/app` for the 2nd run of splunk-sdk
```bash
# for i in msrestazure splunk-sdk futures ; do pip install --upgrade ${i} -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin ; done

# pip install --upgrade splunk-sdk -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin/app
```
- Installed the node.js bits with `npm install` from `$SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin/app`
- `chown -R splunk:splunk $SPLUNK_HOME/etc/apps/TA-Azure_Monitor`
- Enabled the app

I've also restarted Splunk subsequent to the above. I always get:
```plain
Unable to initialize modular input "azure_diagnostic_logs" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_diagnostic_logs: script running failed (exited with code 1).
```

I do not get any errors from the PIP install process and only warnings from NPM for a handful of outdated/unsupported modules.

I have successfully set this add-on up on two separate Splunk 7.1.5 installs. Does this add-on work with 6.5?

**Comment by sebastus** [comment]
code 1 usually means something to do with dependencies. you can try running
the TA from the command line by executing the command that's inside the .sh
file, e.g. azure_diagnostic_logs.sh. look for an error message popping out
in the shell.

**Comment by yorokobi** [comment]
> code 1 usually means something to do with dependencies. you can try running the TA from the command line by executing the command that's inside the .sh file, e.g. azure_diagnostic_logs.sh. look for an error message popping out in the shell.

```bash
[splunk@fwd03] ~/etc/apps/TA-Azure_Monitor/bin % export SPLUNK_HOME=/opt/splunk 

[splunk@fwd03] ~/etc/apps/TA-Azure_Monitor/bin % ./azure_diagnostic_logs.sh    
/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/subs.js:56
        let token;
            ^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:42:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:34:16
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:70:3)
```

**Comment by sebastus** [comment]
ECMAScript 6 introduced 'let'.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

Can you upgrade to a version of node that is post-ECMAScript 6?

If not, I'm sure it wouldn't be too hard to tinker with the code to
eliminate the requirement.

**Comment by yorokobi** [comment]
> ECMAScript 6 introduced 'let'. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let Can you upgrade to a version of node that is post-ECMAScript 6? If not, I'm sure it wouldn't be too hard to tinker with the code to eliminate the requirement.

The error isn't about 'let' it carets 'token'.

Given that my system this works on is the same version of RHEL with the same version of node, I'm disinclined to blame node. The only difference between the two is the version of Enterprise Splunk, which begs the question I asked earlier: What version(s) of Splunk does this add-on support?

I compared the Python module requirements between RHEL, Ubuntu, and Windows and went ahead and added the differences (Markdown and adal) to no effect.

I installed the Azure CLI (even though we don't use the set up script to create the Azure side of things) just in case to no effect. 

I ran the shell script via splunk ( `/opt/splunk/bin/splunk cmd ./azure_diagnostic_logs.sh` ) to no effect.

**Comment by sebastus** [comment]
Hmm. I see what you mean. The TA was written a couple of years ago and has
not been adjusted for any version of Splunk. I'm disinclined to suspect the
Splunk version though, simply because once the node code is running, Splunk
is out of the picture. Splunk's job is to just kick the thing off and then
accept the message flow.

Want to try something? Delete that line. It's only there for linting. The
next if/else will set token to the right value depending on your auth
scheme.

**Comment by sebastus** [comment]
oh - and what version of the TA is working on the other system? That line
"let token" is a recent addition.

**Comment by yorokobi** [comment]
> oh - and what version of the TA is working on the other system? That line "let token" is a recent addition.

Both are using the package labeled as 1.3.1.

If I remark `let token;` the stack trace moves to app/subs.js:120. 

```java
/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/subs.js:120                                                                                                                       
        msRestAzure.loginWithMSI(options).then((token) => {                                                                                                                     
                                                       ^^                                                                                                                       
SyntaxError: Unexpected token =>                                                                                                                                                
    at exports.runInThisContext (vm.js:73:16)                                                                                                                                   
    at Module._compile (module.js:443:25)                                                                                                                                       
    at Object.Module._extensions..js (module.js:478:10)                                                                                                                         
    at Module.load (module.js:355:32)                                                                                                                                           
    at Function.Module._load (module.js:310:12)                                                                                                                                 
    at Module.require (module.js:365:17)                                                                                                                                        
    at require (module.js:384:17)                                                                                                                                               
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:42:12)                                                                           
    at Module._compile (module.js:460:26)                                                                                                                                       
    at Object.Module._extensions..js (module.js:478:10)                                                                                                                         
    at Module.load (module.js:355:32)                                                                                                                                           
    at Function.Module._load (module.js:310:12)                                                                                                                                 
    at Module.require (module.js:365:17)                                                                                                                                        
    at require (module.js:384:17)                                                                                                                                               
    at /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:34:16                                                                                             
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:70:3)
```

If I remark from 120 to 130, the next error is

```java
/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/ms-rest-azure/lib/azureServiceClient.js:6
const async = require('async');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/ms-rest-azure/lib/msRestAzure.js:7:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/subs.js:37:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:42:12)
```

If it isn't the version of Splunk then your suggestion of a missing dependency seems most likely but I'm at a loss to identify what it could be.

**Comment by sebastus** [comment]
re: The next problem with '=>':

That's a javascript arrow function. Also introduced in ECMAScript 6. Also
new code - came at the same time as the 'let token' line.

Are you using MSI auth?

Are you using the same authentication on both boxes?

**Comment by yorokobi** [comment]
> re: The next problem with '=>': That's a javascript arrow function. Also introduced in ECMAScript 6. Also new code - came at the same time as the 'let token' line. Are you using MSI auth? Are you using the same authentication on both boxes?

I updated node to v6.16.0; same error.

We use SPN for authentication but I haven't gotten that far as this is a clean install of the add-on and we do not use the azure-setup script to configure the Azure side.

**Comment by sebastus** [comment]
I checked out an earlier version of node (4.x) and found that both the let
statement and the arrow function work (sort of). So I now doubt that node
is the issue. Sorry for taking you down that rabbit hole.

I assume from your comments about how you installed the TA that you have
some experience with the process. That said, it's a lot different (and more
complicated) than the way I do it:

1. download package from the repo
2. using Splunk UI, install the app from Manage Apps
3. then install dependencies the way you did.

I doubt this is the source of the problem, but it's a difference that you
could check if you have the ambition.

**Comment by yorokobi** [comment]
UI install or CLI install, the effect is the same. .spl packages are renamed .tar.gz files.

I spun up a CentOS 7 VM, installed Enterprise Splunk 6.5.6, installed the Azure Add-on as I described above, ran into the same problem with the diagnostics script. I upgraded Splunk to 7.1.1 and the script ran just fine.

The README.md (and the description on splunkbase.splunk.com) should qualify this add-on as not compatible with Splunk <=6.5.6 (probably <6.6.0 or even <7.0.0 but I didn't test all the versions).

**Comment by yorokobi** [comment]
Splunk ships with node so when Splunk is asked to do something with node.js, it asks itself, not the OS.

HT: Splunk Trust for pointing this out to me

Splunk v6.5.6 
```bash
$ /opt/splunk/bin/splunk cmd node -v
v0.12.7
```
Splunk 7.1.1
```bash
$ /opt/splunk/bin/splunk cmd node -v
v6.12.2
```
Splunk 7.2.3
```bash
$ /opt/splunk/bin/splunk cmd node -v
v6.12.2
```

**Comment by Robbie1194** [comment]
I'm having very similar issues as mentioned above, I can only see the "Azure Monitor Metrics" data input and get the error message in Splunk via the UI:

"Unable to initialize modular input "azure_diagnostic_logs" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_diagnostic_logs: script running failed (exited with code 1)."

I also get the following messages when I try and run npm install as root or as Splunk:

[root@splunk-hf bin]# npm install
npm WARN enoent ENOENT: no such file or directory, open '/opt/splunk/etc/apps/TA-Azure_Monitor/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.

Can anyone advise how to fix these errors?

**Comment by sebastus** [comment]
The "npm WARN" messages can be ignored.

You need to run npm install from the bin/app directory. You ran it inside
bin.

**Comment by Robbie1194** [comment]
For anyone that has the errors I mentioned above, all you need to do is:

is move packages.json from the apps directory within the bin directory and then run npm install again. 

cd /opt/splunk/etc/app/TA-Azure_Monitor/bin/
cp /opt/splunk/etc/app/TA-Azure_Monitor/bin/apps/packages.json ../
npm install
