### ISSUE TITLE
Azure AD logs -- Splunk data not matching data in Azure Portal

### ISSUE THREAD

**Issue by rmmalon** [microsoft/AzureMonitorAddonForSplunk#117]
Example: in the Azure portal, for a specified date/time period, Azure AD Audit Logs may list 800 entries but the same time period in Splunk shows 780 entries.  A closer comparison shows occasional gaps in the data in Splunk compared to the data in the Azure portal.

Also, there is another add-on named "Azure Event Hubs Log Integrator" similar to this add-on but it uses Azure blob storage via the 'capture option' for an event hub.  We have not tried that add-on because this add-on appears to be the Microsoft preferred approach - is that correct?

**Comment by rmmalon** [comment]
The gaps we are seeing are for Azure AD SIGNIN log entries where the missing log entries appear to be of the same source type and structure as other SIGNIN log entries that make it into Splunk without problems.  Are there any specific fields within a SIGNIN log entry that may cause Splunk to drop that log entry?

**Comment by rmmalon** [comment]
With debug on for ExecProc, we are seeing the following block of -0700 errors related to azure_activity_log.sh every 5 minutes (chronological order is from bottom to top):

at TLSSocket.Readable.push (_stream_readable.js:134:10)
at readableAddChunk (_stream_readable.js:176:18)
at TLSSocket.emit (events.js:188:7)
at emitOne (events.js:96:13)
at TLSSocket.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/transport/tls_transport.js:29:49)
at TlsTransport.emit (events.js:188:7)
at emitOne (events.js:96:13)
at TlsTransport.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:516:38)
at Connection._receiveData (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:358:8)
at Connection._receiveAny (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:427:12)
at Connection.emit (events.js:188:7)
at emitOne (events.js:101:20)
at Connection._processFrameEH (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:224:49)
at Session._processFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:352:63)
at Session._processTransferFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:419:45)
at ReceiverLink._messageReceived (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/receiver_link.js:203:8)
at ReceiverLink.emit (events.js:191:7)
at emitTwo (events.js:106:13)
at ehMessageHandler (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:
at Array.forEach (native)
at /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:576:17
at messageHandler (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:36
TypeError: Cannot read property 'toUpperCase' of undefined
^
var operationNameRaw = data.operationName.toUpperCase() || '';
/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:367

**Comment by sebastus** [comment]
The TA is receiving data in a format it doesn't recognise. Are you up for a
little debugging?

Insert these lines:

if (data.operationName === undefined) {
Logger.debug(name, String.format('data from eh is: {0}', JSON.stringify(data
)));
}

after line 328 of azure_monitor_logs.js. (this file is in the TA
folder/bin/app)

It should say this:

Logger.debug(name, String.format('streamEvents.messageHandler got data for
data input named: {0}', name));

Every message from event hub should have an operation name. I'm very
curious to see what's coming down the pipe.

**Comment by rmmalon** [comment]
Lines have been added ... now getting
TypeError: Cannot read property 'format' of undefined

**Comment by sebastus** [comment]
the text is case sensitive. "String", not "string".

**Comment by rmmalon** [comment]
Typo corrected - can you give me some help as to what I am looking for in the Splunk logs now? key words? -thx

**Comment by sebastus** [comment]
search for "data from eh is".

**Comment by rmmalon** [comment]
So it looks like those errors are related to the Azure Key Vault:

data from eh is: {"count":1,"total":1,"minimum":1,"maximum":1,"average":1,"resourceId":"/SUBSCRIPTIONS/####/RESOURCEGROUPS/####/PROVIDERS/MICROSOFT.KEYVAULT/VAULTS/####","time":"2019-01-29T20:39:00.0000000Z","metricName":"ServiceApiHit","timeGrain":"PT1M"}

**Comment by sebastus** [comment]
That looks like a record that comes from metrics. Did you happen to route
some metrics to the activity log event hub?

**Comment by rmmalon** [comment]
It is diagnostic settings from a key vault routed to the event hub (one of my colleagues set it up).  So mystery data solved but unfortunately not helping with the problem of missing data from SIGNIN logs ...

**Comment by rmmalon** [comment]
For the key vault diag settings going to the eh, I left log>auditevent on but turned off metrics>allmetrics ... will see if that clears the error ...

**Comment by sebastus** [comment]
Any metrics that are offered to go through an event hub should not be. Any
metrics should be consumed via the metrics data input.

re: signin logs. now that metrics errors are understood and eliminated,
maybe you can find errors for the 20 missing ones?
