### ISSUE TITLE
TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by jakemarston** [Microsoft/AzureMonitorAddonForSplunk#122]
Hi,

I've followed all of the documentation and can't get this working. See below log output.

```
02-11-2019 09:52:19.846 -0800 ERROR ExecProcessor - message from "python "F:\Program Files\Splunk\etc\apps\rest_ta\bin\rest.py"" Exception performing request: 
02-11-2019 09:53:29.971 -0800 ERROR ExecProcessor - message from "python "F:\Program Files\Splunk\etc\apps\rest_ta\bin\rest.py"" Exception performing request: 
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd"" F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\app\node_modules\amqp10\lib\frames.js:64
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""   stream.write(buffer, callback);
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""         ^
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd"" TypeError: Cannot read property 'write' of null
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at Object.frames.writeFrame (F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\app\node_modules\amqp10\lib\frames.js:64:9)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at Connection.sendFrame (F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\app\node_modules\amqp10\lib\connection.js:329:10)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at ReceiverLink.Link.attach (F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\app\node_modules\amqp10\lib\link.js:152:27)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at Timeout._onTimeout (F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\app\node_modules\amqp10\lib\link.js:270:12)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at ontimeout (timers.js:386:11)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at tryOnTimeout (timers.js:250:5)
02-11-2019 09:54:03.482 -0800 ERROR ExecProcessor - message from ""F:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd""     at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by sebastus** [comment]
Ensure that only hubs that exist in the hub namespace are listed in
TA-folder/bin/app/hubs.json.

**Comment by sebastus** [comment]
One more thing. "insights-operational-logs" does not go in hub.json. That hub is for the Activity Log data input.

**Comment by jakemarston** [comment]
I've updated my `hubs.json` file and now it only includes the two hubs listed below, however I'm still receiving the same error message. 

```
{
    "insights-logs-operational-logs": "resourceId",
    "insights-logs-alerts": "resourceId"
}
```

**Comment by sebastus** [comment]
I think you have a spelling error. Shouldn't it be
"insights-logs-operationallogs"? (eliminate the last - )

**Comment by jakemarston** [comment]
I've tried both. In the Azure Portal it has the '-'.
![image](https://user-images.githubusercontent.com/35906492/52880305-73010900-3116-11e9-8fb9-721df8114736.png)

**Comment by sebastus** [comment]
Ah - that one. :)

insights-operational-logs is the Activity Logs hub. It should not be in
hubs.json.

https://github.com/Microsoft/AzureMonitorAddonForSplunk/wiki/Configuration-of-Splunk#hubsjson
