### ISSUE TITLE
Error with azure_activity_log.sh

### ISSUE THREAD

**Issue by trolleyboy** [microsoft/AzureMonitorAddonForSplunk#152]
Hi there,
We're getting these messages when Activity Log Monitor is enabled on a new Heavy Forwarder that is replacing the old one (which has been working fine).  

```07-26-2019 11:43:41.494 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:367
07-26-2019 11:43:41.494 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"             var operationNameRaw = data.operationName.toUpperCase() || '';
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"                                                      ^
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" TypeError: Cannot read property 'toUpperCase' of undefined
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at messageHandler (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:367:54)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:576:17
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Array.forEach (native)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ehMessageHandler (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:575:21)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at emitTwo (events.js:106:13)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ReceiverLink.emit (events.js:191:7)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ReceiverLink._messageReceived (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/receiver_link.js:203:8)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Session._processTransferFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:419:45)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Session._processFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:352:63)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection._processFrameEH (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/session.js:224:49)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at emitOne (events.js:101:20)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection.emit (events.js:188:7)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection._receiveAny (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connnection.js:427:12)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection._receiveData (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:358:8)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at TlsTransport.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:516:38)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at emitOne (events.js:96:13)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at TlsTransport.emit (events.js:188:7)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at TLSSocket.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/transport/tls_transport.js:29:49)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at emitOne (events.js:96:13)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at TLSSocket.emit (events.js:188:7)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at readableAddChunk (_stream_readable.js:176:18)
07-26-2019 11:43:41.495 +1200 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at TLSSocket.Readable.push (_stream_readable.js:134:10)
```

The main difference I can think of is that the new VM is located in Azure and is using an MSI for auth.  That is working fine with Metrics and Diagnostic logs.  (The old VM is on-prem, using SPN). 

Diagnostics Logs is configured to connect to the same Event Hub namespace and is pulling in data from the hubs listed in hubs.json as expected.  As per the Wiki, insights-operational-logs is not listed in hubs.json.  
It's just the Activity Log that is causing a problem on this new VM.  

I saw issue #117 which has similar errors, but adding the extra logging code didn't seem to produce any extra output.  

EDIT:  I forgot to mention, the Data Inputs on the old VM related to this Add-on have been disabled.  So there should be no "conflicts". 

Any help/thoughts appreciated.

**Comment by sebastus** [comment]
What Azure resource types are you monitoring with diagnostic logs?

**Comment by trolleyboy** [comment]
> What Azure resource types are you monitoring with diagnostic logs?

```
Microsoft.ApiManagement/Service
Microsoft.SQL/Servers
Microsoft.Logic/Workflows
```

**Comment by sebastus** [comment]
can you switch off monitoring for the ApiManagement service? see if that
fixes it. I had to fix the function recently for a few new resource types -
they don't conform to the standard message format.

**Comment by trolleyboy** [comment]
That seems to get Activity Log working. Re-enabling the ApiManagement diagnostics to flow through EventHub breaks Activity Log again.

**Comment by sebastus** [comment]
thanks for the feedback. It's on my list.

**Comment by sebastus** [comment]
What version of the TA are you running? This line of code:

```var operationNameRaw = data.operationName.toUpperCase() || '';```

no longer exists in v1.3.2.

**Comment by trolleyboy** [comment]
v1.3.2 is installed (it was a fresh install on this version)
