### ISSUE TITLE
ImportError: No module named splunklib.six

### ISSUE THREAD

**Issue by d0t1q** [microsoft/AzureMonitorAddonForSplunk#176]
Can't seem to get the module running. Getting the error

`Unable to initialize modular input "azure_monitor_metrics" defined in the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1)..` 

Noticed the following error in my splunkd log

splunkd.log:04-21-2020 00:31:14.468 +0000 INFO  SpecFiles - Found external scheme definition for 

```
stanza="azure_monitor_metrics://" from spec file="/opt/splunk/etc/apps/TA-Azure_Monitor/README/inputs.conf.spec" with parameters="SPNTenantID, SPNApplicationId, SPNApplicationKey, SubscriptionId, vaultName, secretName, secretVersion"
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:  Traceback (most recent call last):
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:    File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py", line 126, in <module>
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:      sys.exit(AzureMonitorMetrics().run(sys.argv))
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:    File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/script.py", line 56, in run
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:      return self.run_script(args, EventWriter(), sys.stdin)
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:    File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/event_writer.py", line 49, in __init__
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:      self._out = TextIOWrapper(output)
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - <stderr> Introspecting scheme=azure_monitor_metrics:  AttributeError: 'file' object has no attribute 'readable'
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1).
splunkd.log:04-21-2020 00:31:15.608 +0000 ERROR ModularInputs - Unable to initialize modular input "azure_monitor_metrics" defined in the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1)..
```

So I ran the script manually  and recieved the following output

```
$ splunk cmd python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/event_writer.py
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/event_writer.py", line 19, in <module>
    from splunklib.six import ensure_text
ImportError: No module named splunklib.six

```
but I have the LIB installed and in the six.py does exist

![image](https://user-images.githubusercontent.com/8010159/79814972-64bf0600-8334-11ea-9d16-915b05e23961.png)

Running the azure_monitor_metrics script returns the following

$ splunk cmd python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py
```
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py", line 126, in <module>
    sys.exit(AzureMonitorMetrics().run(sys.argv))
  File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/script.py", line 56, in run
    return self.run_script(args, EventWriter(), sys.stdin)
  File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/modularinput/event_writer.py", line 49, in __init__
    self._out = TextIOWrapper(output)
AttributeError: 'file' object has no attribute 'readable'
```

I've ran through installing the deps and running npm, so I'm not sure if I've missed something. 

OS: Rhel 7 
Splunk Ver: 8.0.1

**Comment by fredzh26** [comment]
I have same issue (same os but on splunk 7.1.2) 
Wonder if there is anyone has updates for this? 
Thanks,

**Comment by lastaill** [comment]
We're also experiencing this issue. Haven't found a fix for this yet. 
Any ideas?
