### ISSUE TITLE
Does it work on Splunk Cloud?

### ISSUE THREAD

**Issue by fzavalloni** [microsoft/AzureMonitorAddonForSplunk#179]
Hi,

Does it work on Splunk Cloud? I have tried to upload and install it but it has been rejected.

```
Failures will block the Cloud Vetting. They must be fixed.
check_validate_modular_inputs_scheme_args
The scheme is not in a valid format(json or xml). Scheme: `module.js:550
    throw err;
    ^

Error: Cannot find module 'splunk-sdk'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:32:20
    at Object.<anonymous> (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:70:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
` File: bin/azure_diagnostic_logs.sh
```

**Comment by fzavalloni** [comment]
Nope. They don't.
I submitted a support ticket to them and they rejected the application.
