### ISSUE TITLE
Impossible to use Azure Monitor and DBconnect togheter.

### ISSUE THREAD

**Issue by lukasmrtvy** [microsoft/AzureMonitorAddonForSplunk#97]
Seems that `pip install futures -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin` install requests (dependecny) to this location.

DBconnect needs requests package and fails to:
```
<?xml version="1.0" encoding="UTF-8"?> <response> <messages> <msg type="WARN">Traceback (most recent call last): File "/opt/splunk/bin/rest_handler.py", line 79, in &lt;module&gt; print splunk.rest.dispatch(**params) File "/opt/splunk/lib/python2.7/site-packages/splunk/rest/__init__.py", line 149, in dispatch module = __import__('splunk.rest.external.%s' % parts[0], None, None, parts[0]) File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbxproxy.py", line 4, in &lt;module&gt; import requests File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/requests/__init__.py", line 43, in &lt;module&gt; import urllib3 ImportError: No module named urllib3 </msg> </messages> </response>
```

There is possible to do:
```
cp -R /opt/splunk/etc/apps/TA-Azure_Monitor/bin/urllib3 /opt/splunk/etc/apps/splunk_app_db_connect/bin/
cp -R /opt/splunk/etc/apps/TA-Azure_Monitor/bin/chardet /opt/splunk/etc/apps/splunk_app_db_connect/bin/
cp -R /opt/splunk/etc/apps/TA-Azure_Monitor/bin/certifi /opt/splunk/etc/apps/splunk_app_db_connect/bin/
cp -R /opt/splunk/etc/apps/TA-Azure_Monitor/bin/idna /opt/splunk/etc/apps/splunk_app_db_connect/bin/
```
, but DBconnect will fail eventualy to:

```
<?xml version="1.0" encoding="UTF-8"?> <response> <messages> <msg type="WARN">Traceback (most recent call last): File "/opt/splunk/bin/rest_handler.py", line 79, in &lt;module&gt; print splunk.rest.dispatch(**params) File "/opt/splunk/lib/python2.7/site-packages/splunk/rest/__init__.py", line 149, in dispatch module = __import__('splunk.rest.external.%s' % parts[0], None, None, parts[0]) File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbxproxy.py", line 7, in &lt;module&gt; from dbx_settings import Settings File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbx_settings.py", line 10, in &lt;module&gt; import splunklib.client as client File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/__init__.py", line 18, in &lt;module&gt; from splunklib.six.moves import map ImportError: No module named six.moves </msg> </messages> </response>
```
even if I try to do:
```
cp -R /opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib /opt/splunk/etc/apps/splunk_app_db_connect/bin/
```

**Comment by lukasmrtvy** [comment]
Duplicate ? https://github.com/Microsoft/AzureMonitorAddonForSplunk/issues/56
